# Generated by Django 5.0 on 2025-10-23 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_booking_news_tour_userprofile_delete_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['name'], 'verbose_name': 'Điểm đến', 'verbose_name_plural': 'Danh sách điểm đến'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tour du lịch', 'verbose_name_plural': 'Danh sách tour'},
        ),
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cccd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phân loại'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Nổi bật'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='location',
            field=models.CharField(blank=True, max_length=150, verbose_name='Vị trí'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Tên điểm đến'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tour',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='home.destination', verbose_name='Điểm đến'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.CharField(blank=True, max_length=100, verbose_name='Thời lượng'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Tour nổi bật'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='Ảnh tour'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='schedule',
            field=models.TextField(blank=True, verbose_name='Lịch trình'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Tên tour'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Số sao (1–5)')),
                ('comment', models.TextField(blank=True, verbose_name='Nhận xét')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.tour', verbose_name='Tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Danh sách đánh giá',
                'ordering': ['-created_at'],
                'unique_together': {('tour', 'user')},
            },
        ),
    ]
