# Generated by Django 5.0 on 2025-11-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='is_domestic',
            field=models.BooleanField(default=True, verbose_name='Thuộc Việt Nam (Trong nước)'),
        ),
    ]
