# Generated by Django 5.0 on 2025-11-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_destination_is_domestic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='is_domestic',
        ),
        migrations.AddField(
            model_name='destination',
            name='region',
            field=models.CharField(choices=[('domestic', 'Trong nước'), ('international', 'Nước ngoài')], default='domestic', max_length=20, verbose_name='Khu vực'),
        ),
    ]
