# Generated by Django 5.0 on 2025-11-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_destination_is_domestic_destination_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='region',
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('domestic', 'Trong nước'), ('foreign', 'Ngoài nước')], default='domestic', max_length=20, verbose_name='Loại tour'),
        ),
    ]
